system_node_rate : 1000
system_sample_time : 0.2
system_param_K : 53.1
system_param_T : 1.0
system_initial_cond :  10.0
system_max_speed : 13.0
system_min_input : 1

#system_node_rate : 100
#system_sample_time : 0.002
#system_param_K : 13.1
#system_param_T : 0.04
#system_initial_cond :  0.0
#system_max_speed : 13.0
#system_min_input : 0.05
